//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakitka2021v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int CarID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<float> Price { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Companies Companies { get; set; }
    }
}
